{% set version = "0.1.5" %}

package:
  name: ibis-mssql
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/ibis-mssql/ibis-mssql-{{ version }}.tar.gz
  sha256: 83d5483aff2fc15a62f5a96ccc38565a1e19194e7123f0d792217f6c1048576e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - ibis-framework
    - sqlalchemy
    - pyodbc

test:
  imports:
    - ibis_mssql

about:
  home: https://github.com/quansight/ibis-mssql
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Ibis backend for MSSQL
  dev_url: https://github.com/quansight/ibis-mssql

extra:
  recipe-maintainers:
    - costrouc
